### ISSUE TITLE
mac 启动报错，quickcut error

### ISSUE THREAD

**Issue by wansuiye09** [HaujetZhao/QuickCut#29]

**Comment by HaujetZhao** [comment]
只能自己搭建环境，打包了。现在 mac 的志愿者只有一个，又因学业，不能打包了。

**Comment by shniubobo** [comment]
请问能不能详细描述一下问题，或者上一张截图之类的，不然不好确定原因

**Comment by Jaylee89** [comment]
我这边是缺少一个包的问题, 在启动的时候，已解决。
```
Traceback (most recent call last):
  File "QuickCut.py", line 23, in <module>
    import pymediainfo
ModuleNotFoundError: No module named 'pymediainfo'
```
```
python3 -m pip install pymediainfo
```

**Comment by Jaylee89** [comment]
> 我这边是缺少一个包的问题, 在启动的时候，已解决。
> 
> ```
> Traceback (most recent call last):
>   File "QuickCut.py", line 23, in <module>
>     import pymediainfo
> ModuleNotFoundError: No module named 'pymediainfo'
> ```
> 
> ```
> python3 -m pip install pymediainfo
> ```

@HaujetZhao , raised a PR to solve the dependency issue, please take a look:
https://github.com/HaujetZhao/QuickCut/pull/42
