### ISSUE TITLE
mac上pip安装了跑不起来

### ISSUE THREAD

**Issue by junmoxiao** [HaujetZhao/QuickCut#38]
```
mkvirtualenv --python=python3 quickcut
pip install Quick-Cut
```
安装完之后执行Quick-Cut会提示如下
```
(quickcut) /usr/local ./bin/Quick-Cut
Traceback (most recent call last):
  File "./bin/Quick-Cut", line 5, in <module>
    from QuickCut.QuickCut import main
  File "/usr/local/lib/python3.8/site-packages/QuickCut/QuickCut.py", line 23, in <module>
    import pymediainfo
ModuleNotFoundError: No module named 'pymediainfo'
```
但是pymediainfo这个是已经安装了的，奇怪

**Comment by xuanskyer** [comment]
same Q
